### ISSUE TITLE
Program fails to start "panicked at compile_shader"

### ISSUE THREAD

**Issue by petevine** [PistonDevelopers/opengl_graphics#223]
That toy game used to work a few months ago without a problem on this soft Mesa `OpenGL 2` ARM [system](https://gist.github.com/petevine/73b0b50091e6c7121699), but now:

```rust

$ RUST_BACKTRACE=1 target/debug/rocket

thread '<main>' panicked at 'compile_shader: 0:1(1): error: syntax error, unexpected $undefined 
', /tmp/.cargo/registry/src/github.com-48ad6e4054423464/piston2d-opengl_graphics-0.23.0/src/back_end.rs:56
stack backtrace:
   1: 0xb6f87333 - sys::backtrace::tracing::imp::write::h5fa72351789a20eb4nu
   2: 0xb6f8997f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42804
   3: 0xb6f894d3 - panicking::default_handler::h5c31f6d656fe4f20yHy
   4: 0xb6f7ebd3 - sys_common::unwind::begin_unwind_inner::h292ecb37a0508c3bCgt
   5: 0xb6f7f11f - sys_common::unwind::begin_unwind_fmt::h89eb0d66b9a05c98Ift
   6: 0xb6de53f7 - back_end::Colored::new::h2f6cc0a880cc1169Xva
                at /tmp/rocket-master/<std macros>:8
   7: 0xb6df177f - back_end::GlGraphics::new::h0a644431e4e0f2fe6Fa
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/piston2d-opengl_graphics-0.23.0/src/back_end.rs:225
   8: 0xb6cfc34f - main::h057f6eeb9f369edagPa
                at src/main.rs:33

```

It works fine on an x86 laptop (32-bit mode) with these hardware OGL 2.1 [specs.](https://gist.github.com/petevine/74f8a09fbd1238255a13)

Any ideas?

Between runs, it can also print **unexpected** `NEW_IDENTIFIER` or `INTCONSTANT` instead of `$undefined`

**Comment by xSke** [comment]
I'm getting the same issue with opengl_graphics 0.28.1. The error randomly changes slightly, sometimes it's a different syntax error. Always on line 141 of back_end.rs though.
